# Generated by Django 3.0.5 on 2020-04-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='introduce',
            field=models.TextField(blank=True),
        ),
    ]
