# Generated by Django 3.0.5 on 2020-04-10 21:10

from django.db import migrations, models
import django.db.models.deletion
import subjects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member')),
            ],
            options={
                'db_table': 'member_subject',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=45)),
                ('rating', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('sub_image', models.ImageField(upload_to=subjects.models.sub_image_path)),
                ('language', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(related_name='subjects', through='subjects.ClassRoom', to='accounts.Member')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_lectures', to='accounts.Member')),
            ],
            options={
                'db_table': 'subjects',
            },
        ),
        migrations.CreateModel(
            name='SubVideoUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_video', models.URLField()),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='subjects.Subject')),
            ],
            options={
                'db_table': 'subvideos',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='subjects.Subject'),
        ),
    ]
