# Generated by Django 3.0.5 on 2020-04-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.IntegerField()),
                ('sub_id', models.IntegerField()),
                ('price', models.IntegerField()),
                ('result', models.BooleanField()),
                ('pay_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orderlogs',
            },
        ),
    ]
